# Aria Cron Jobs Definition
# These are injected at container startup by openclaw-entrypoint.sh
# Format matches `openclaw cron add` CLI parameters
# NOTE: All times are in UTC! Server runs PST (UTC-8)
#   To schedule 8am PST, use 16 (8+8=16 UTC)
#   To schedule 11pm PST, use 7 next day (23+8=31=7 UTC)

jobs:
  - name: work_cycle
    every: "15m"
    message: "Read HEARTBEAT.md work_cycle section. Check goals, pick highest priority, make progress, log activity."
    agent: main
    session: isolated

  - name: hourly_goal_check
    cron: "0 * * * *"
    message: "Read HEARTBEAT.md hourly_goal_check section. Check current hourly goal, attempt completion, create next goal."
    agent: main
    session: isolated

  - name: six_hour_review
    cron: "0 0,6,12,18 * * *"
    message: "Read HEARTBEAT.md six_hour_review section. Analyze last 6h, adjust priorities, generate insights."
    agent: main
    session: isolated

  - name: moltbook_post
    cron: "0 1,13 * * *"
    message: "Read HEARTBEAT.md moltbook_post section. Use social skill to post a meaningful update to MoltBook."
    agent: main
    session: isolated

  - name: morning_checkin
    cron: "0 16 * * *"
    message: "Read HEARTBEAT.md morning_checkin section. Good morning! Review overnight changes, set today priorities."
    agent: main
    session: isolated

  - name: daily_reflection
    cron: "0 7 * * *"
    message: "Read HEARTBEAT.md daily_reflection section. Review full day, summarize achievements, note tomorrow priorities."
    agent: main
    session: isolated

  - name: weekly_summary
    cron: "0 2 * * 1"
    message: "Read HEARTBEAT.md weekly_summary section. Generate comprehensive weekly report with metrics, learnings, and next week goals."
    agent: main
    session: isolated
