"""Gateway abstraction layer for legacy phase-out (S-31).

This module provides an abstract interface for LLM gateway communication.
Currently implemented by LegacyGateway; NativeGateway planned for v1.3.
"""
from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional
import logging
import time

logger = logging.getLogger("aria.gateway")


class GatewayInterface(ABC):
    """Abstract gateway for LLM communication."""

    @abstractmethod
    async def send_message(
        self, message: str, tools: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        """Send a message through the gateway and return the response."""
        ...

    @abstractmethod
    async def get_system_prompt(self) -> str:
        """Retrieve the current system prompt from the gateway."""
        ...

    @abstractmethod
    async def list_tools(self) -> List[Dict[str, Any]]:
        """List available tools registered with the gateway."""
        ...


class LegacyGateway(GatewayInterface):
    """Current implementation — delegates to aria-api container.

    The aria-api service runs at port 8000 (docker-compose.yml:49).
    Config generated by aria_models/config.py.
    """

    def __init__(self, base_url: str = "http://aria-api:8000"):
        self.base_url = base_url
        self._latency_samples: List[float] = []

    async def send_message(
        self, message: str, tools: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        start = time.monotonic()
        try:
            # TODO: wire to actual Aria REST or WebSocket API
            raise NotImplementedError(
                "LegacyGateway.send_message() — wire to Aria API in v1.3"
            )
        finally:
            elapsed = time.monotonic() - start
            self._latency_samples.append(elapsed)
            logger.info(
                "gateway.request",
                extra={"latency_ms": round(elapsed * 1000, 2)},
            )

    async def get_system_prompt(self) -> str:
        # Read from mounted file (set by S-27)
        from pathlib import Path
        import os

        prompt_file = os.environ.get("ARIA_SYSTEM_PROMPT_FILE", "")
        if prompt_file:
            p = Path(prompt_file)
            if p.exists():
                return p.read_text(encoding="utf-8")
        return "(default Aria prompt — not customized)"

    async def list_tools(self) -> List[Dict[str, Any]]:
        # TODO: query Aria /tools endpoint
        raise NotImplementedError("LegacyGateway.list_tools() — v1.3")

    def get_latency_stats(self) -> Dict[str, float]:
        """Return latency statistics for phase-out analysis."""
        if not self._latency_samples:
            return {"avg_ms": 0, "p95_ms": 0, "p99_ms": 0, "count": 0}
        s = sorted(self._latency_samples)
        n = len(s)
        return {
            "avg_ms": round(sum(s) / n * 1000, 2),
            "p95_ms": round(s[int(n * 0.95)] * 1000, 2) if n > 1 else round(s[0] * 1000, 2),
            "p99_ms": round(s[int(n * 0.99)] * 1000, 2) if n > 1 else round(s[0] * 1000, 2),
            "count": n,
        }
